//! Per-stage container network management.
//!
//! Three responsibilities:
//!   1. Materialise the per-stage allowlist file that the firewall
//!      script reads from inside the container (mounted RO).
//!   2. Create / remove the per-stage Docker/Podman/Apple-Container
//!      network so each session is in its own L3 namespace.
//!
//! The allowlist file is owned by the host and mounted read-only; the
//! agent process inside the container cannot edit it (per finding #16).

use anyhow::{bail, Context, Result};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use super::runtime::Runtime;
use crate::plan::schema::NetworkConfig;

/// Write the host-side allowlist file consumed by the firewall script.
///
/// File layout: `<work_dir>/network/allowed_domains.txt`. One domain per
/// line, header comment, allowed_domains then additional_domains.
pub fn write_allowlist(work_dir: &Path, network: &NetworkConfig) -> Result<PathBuf> {
    let dir = work_dir.join("network");
    fs::create_dir_all(&dir).with_context(|| {
        format!(
            "Failed to create network allowlist directory at {}",
            dir.display()
        )
    })?;
    let path = dir.join("allowed_domains.txt");

    let mut content = String::new();
    content.push_str("# Generated by loom; do not edit by hand.\n");
    content.push_str("# Configure via plan: loom.sandbox.network.allowed_domains\n");
    for d in &network.allowed_domains {
        content.push_str(d);
        content.push('\n');
    }
    for d in &network.additional_domains {
        content.push_str(d);
        content.push('\n');
    }

    fs::write(&path, content)
        .with_context(|| format!("Failed to write allowlist to {}", path.display()))?;
    Ok(path)
}

/// Create a per-stage container network if it does not exist.
///
/// Idempotent: "already exists" errors are silently ignored.
pub fn ensure_network(runtime: &Runtime, stage_id: &str) -> Result<()> {
    let name = network_name(stage_id);
    let output = Command::new(runtime.binary())
        .args(["network", "create", &name])
        .output()
        .with_context(|| {
            format!(
                "Failed to invoke `{} network create {name}`",
                runtime.binary()
            )
        })?;
    if output.status.success() {
        return Ok(());
    }
    let stderr = String::from_utf8_lossy(&output.stderr).to_ascii_lowercase();
    if stderr.contains("already exists") || stderr.contains("already in use") {
        return Ok(());
    }
    bail!(
        "`{} network create {name}` failed: {}",
        runtime.binary(),
        String::from_utf8_lossy(&output.stderr).trim()
    );
}

/// Remove a per-stage container network. Best-effort: missing networks
/// are not an error.
pub fn remove_network(runtime: &Runtime, stage_id: &str) -> Result<()> {
    let name = network_name(stage_id);
    let output = Command::new(runtime.binary())
        .args(["network", "rm", &name])
        .output()
        .with_context(|| format!("Failed to invoke `{} network rm {name}`", runtime.binary()))?;
    if output.status.success() {
        return Ok(());
    }
    let stderr = String::from_utf8_lossy(&output.stderr).to_ascii_lowercase();
    if stderr.contains("no such") || stderr.contains("not found") {
        return Ok(());
    }
    // Non-fatal: log via tracing but don't bail (caller is in cleanup paths).
    tracing::warn!(
        runtime = %runtime.binary(),
        network = %name,
        stderr = %String::from_utf8_lossy(&output.stderr).trim(),
        "Failed to remove container network"
    );
    Ok(())
}

fn network_name(stage_id: &str) -> String {
    format!("loom-net-{stage_id}")
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn empty_net() -> NetworkConfig {
        NetworkConfig::default()
    }

    #[test]
    fn write_allowlist_creates_directory_and_file() {
        let temp = TempDir::new().unwrap();
        let path = write_allowlist(temp.path(), &empty_net()).unwrap();
        assert!(path.exists());
        let content = fs::read_to_string(&path).unwrap();
        assert!(content.contains("Generated by loom"));
    }

    #[test]
    fn write_allowlist_sparse_includes_allowed_and_additional() {
        let temp = TempDir::new().unwrap();
        let n = NetworkConfig {
            allowed_domains: vec!["example.com".into()],
            additional_domains: vec!["extra.com".into()],
            ..Default::default()
        };
        let path = write_allowlist(temp.path(), &n).unwrap();
        let content = fs::read_to_string(&path).unwrap();
        assert!(content.contains("example.com"));
        assert!(content.contains("extra.com"));
    }

    #[test]
    fn write_allowlist_large_input_round_trips() {
        let temp = TempDir::new().unwrap();
        let mut n = NetworkConfig::default();
        for i in 0..500 {
            n.allowed_domains.push(format!("host{i}.example.com"));
        }
        let path = write_allowlist(temp.path(), &n).unwrap();
        let content = fs::read_to_string(&path).unwrap();
        assert!(content.contains("host0.example.com"));
        assert!(content.contains("host499.example.com"));
    }

    #[test]
    fn network_name_format() {
        assert_eq!(network_name("stage-x"), "loom-net-stage-x");
    }

    // Shell-syntax checks for the embedded scripts. Resolve paths via
    // CARGO_MANIFEST_DIR so the test is independent of the process CWD —
    // concurrent #[serial] tests in other modules mutate cwd into a
    // TempDir, which would otherwise make this assertion flaky.
    #[test]
    fn firewall_script_has_valid_bash_syntax() {
        let script = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("resources/firewall.sh");
        let status = std::process::Command::new("bash")
            .arg("-n")
            .arg(&script)
            .status();
        // Skip if bash not present (CI without bash).
        if let Ok(status) = status {
            assert!(status.success(), "firewall.sh failed bash -n");
        }
    }

    #[test]
    fn entrypoint_script_has_valid_bash_syntax() {
        let script =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("resources/entrypoint.sh");
        let status = std::process::Command::new("bash")
            .arg("-n")
            .arg(&script)
            .status();
        if let Ok(status) = status {
            assert!(status.success(), "entrypoint.sh failed bash -n");
        }
    }

    // ensure_network idempotency test gated on runtime availability.
    #[test]
    fn ensure_network_idempotent_when_runtime_missing() {
        // We don't have docker/podman in unit test CI; just verify the
        // function signature compiles and we can call it. Real
        // idempotency is exercised by integration tests.
        let _ = (Runtime::Docker, "stage-x");
    }
}
