//! Knowledge index (tier 0) generation.
//!
//! `INDEX.md` is a generated map of the knowledge hierarchy: the tier-1
//! summary files plus every tier-2 topic file, grouped by category. It is
//! regenerated by [`write_index`] whenever a hierarchical knowledge dir is
//! written to (see `KnowledgeDir::append_target` /
//! `KnowledgeDir::replace_section_target`) or explicitly via
//! `loom knowledge index`.

use super::types::{KnowledgeFile, INDEX_FILENAME};
use anyhow::{Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

/// Marker at the top of a generated `INDEX.md` so a human or agent knows not
/// to hand-edit it — edits are lost the next time the index is regenerated.
pub const GENERATED_MARKER: &str =
    "<!-- generated by `loom knowledge index` — do not edit by hand -->";

/// A single tier-2 topic file discovered under a category directory.
#[derive(Debug, Clone)]
pub struct TopicEntry {
    pub category: KnowledgeFile,
    pub slug: String,
    /// Absolute path on disk.
    pub path: PathBuf,
    /// First `# ` line, without the marker (falls back to the slug).
    pub title: String,
    /// First `> ` line, without the marker (empty if none).
    pub blurb: String,
    pub line_count: usize,
}

impl TopicEntry {
    /// Path of this topic relative to the knowledge root, e.g.
    /// `architecture/merge-flow.md`.
    pub fn relative_path(&self) -> PathBuf {
        PathBuf::from(self.category.dir_name()).join(format!("{}.md", self.slug))
    }
}

/// Turn a hyphen/underscore-separated slug into a title, e.g. `merge-flow` ->
/// `Merge Flow`.
pub fn title_case(slug: &str) -> String {
    slug.split(['-', '_'])
        .filter(|word| !word.is_empty())
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

/// Escape a value for a markdown table cell: a raw `|` would end the cell and
/// break the row, and titles/blurbs come from user-written topic files.
fn escape_cell(value: &str) -> String {
    value.replace('|', "\\|")
}

/// Extract the title (first `# ` line) and blurb (first `> ` line) from a
/// knowledge file's content, falling back to `fallback_title` / empty string.
fn extract_title_and_blurb(content: &str, fallback_title: &str) -> (String, String) {
    let title = content
        .lines()
        .find_map(|line| line.strip_prefix("# "))
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| fallback_title.to_string());
    let blurb = content
        .lines()
        .find_map(|line| line.strip_prefix("> "))
        .map(|s| s.trim().to_string())
        .unwrap_or_default();
    (title, blurb)
}

/// Walk `<root>/<category>/*.md` for every [`KnowledgeFile`] category.
///
/// Skips non-`.md` entries, subdirectories, and dotfiles. A missing category
/// directory is simply skipped, not an error. Results are sorted by
/// (category order as in [`KnowledgeFile::all`], then slug).
pub fn scan_topics(root: &Path) -> Result<Vec<TopicEntry>> {
    let mut topics = Vec::new();

    for category in KnowledgeFile::all() {
        let dir = root.join(category.dir_name());
        if !dir.is_dir() {
            continue;
        }

        let mut category_topics = Vec::new();
        let entries = fs::read_dir(&dir)
            .with_context(|| format!("Failed to read topic directory: {}", dir.display()))?;

        for entry in entries {
            let entry =
                entry.with_context(|| format!("Failed to read entry in {}", dir.display()))?;
            let path = entry.path();

            if !path.is_file() {
                continue;
            }
            let Some(file_name) = path.file_name().and_then(|n| n.to_str()) else {
                continue;
            };
            if file_name.starts_with('.') || !file_name.ends_with(".md") {
                continue;
            }

            let slug = file_name.trim_end_matches(".md").to_string();
            let content = fs::read_to_string(&path)
                .with_context(|| format!("Failed to read topic file: {}", path.display()))?;
            let (title, blurb) = extract_title_and_blurb(&content, &slug);

            category_topics.push(TopicEntry {
                category: *category,
                slug,
                path,
                title,
                blurb,
                line_count: content.lines().count(),
            });
        }

        category_topics.sort_by(|a, b| a.slug.cmp(&b.slug));
        topics.extend(category_topics);
    }

    Ok(topics)
}

/// Render the `INDEX.md` content for `root`. Does not write anything.
pub fn generate_index(root: &Path) -> Result<String> {
    let topics = scan_topics(root)?;
    let mut out = String::new();

    out.push_str(GENERATED_MARKER);
    out.push_str("\n\n# Knowledge Index\n\n");
    out.push_str(
        "> Read this index first, then the tier-1 summary for the area you're working \
         in, then only the tier-2 topics you actually need. Tier-1 files are short \
         summaries with links out; tier-2 files hold the full detail.\n\n",
    );

    out.push_str("## Tier 1 — Summaries\n\n");
    out.push_str("| File | Description | Lines |\n");
    out.push_str("| --- | --- | --- |\n");
    for file_type in KnowledgeFile::all() {
        let path = root.join(file_type.filename());
        if !path.exists() {
            continue;
        }
        let line_count = fs::read_to_string(&path)
            .with_context(|| format!("Failed to read {}", file_type.filename()))?
            .lines()
            .count();
        out.push_str(&format!(
            "| [{name}]({name}) | {desc} | {line_count} |\n",
            name = file_type.filename(),
            desc = file_type.description(),
        ));
    }

    if !topics.is_empty() {
        out.push_str("\n## Tier 2 — Topics\n\n");
        let mut current_category: Option<KnowledgeFile> = None;
        for topic in &topics {
            if current_category != Some(topic.category) {
                // Blank line between the previous category's table and this heading:
                // markdownlint (MD022/MD058) rejects a heading or table without one.
                if current_category.is_some() {
                    out.push('\n');
                }
                out.push_str(&format!("### {}\n\n", topic.category.dir_name()));
                out.push_str("| Topic | Title | Blurb | Lines |\n");
                out.push_str("| --- | --- | --- | --- |\n");
                current_category = Some(topic.category);
            }
            let rel = topic.relative_path().display().to_string();
            out.push_str(&format!(
                "| [{rel}]({rel}) | {} | {} | {} |\n",
                escape_cell(&topic.title),
                escape_cell(&topic.blurb),
                topic.line_count
            ));
        }
    }

    Ok(out)
}

/// Crash-atomically write `<root>/INDEX.md`.
pub fn write_index(root: &Path) -> Result<()> {
    let content = generate_index(root)?;
    let path = root.join(INDEX_FILENAME);
    crate::fs::locking::locked_write(&path, &content)
        .with_context(|| format!("Failed to write {}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::fs::knowledge::dir::KnowledgeDir;
    use tempfile::TempDir;

    #[test]
    fn test_title_case() {
        assert_eq!(title_case("merge-flow"), "Merge Flow");
        assert_eq!(title_case("signal_prefix_cache"), "Signal Prefix Cache");
        assert_eq!(title_case("solo"), "Solo");
    }

    #[test]
    fn test_scan_topics_reads_title_blurb_and_ignores_non_markdown() {
        let temp = TempDir::new().unwrap();
        let root = temp.path();
        let arch_dir = root.join("architecture");
        fs::create_dir_all(&arch_dir).unwrap();
        fs::write(
            arch_dir.join("merge-flow.md"),
            "# Merge Flow\n\n> How stages merge back to the base branch.\n\nBody line.\n",
        )
        .unwrap();
        // Non-markdown file must be ignored.
        fs::write(arch_dir.join("notes.txt"), "ignore me").unwrap();
        // Dotfile must be ignored.
        fs::write(arch_dir.join(".hidden.md"), "# Hidden\n").unwrap();

        let topics = scan_topics(root).unwrap();
        assert_eq!(topics.len(), 1);
        let topic = &topics[0];
        assert_eq!(topic.slug, "merge-flow");
        assert_eq!(topic.title, "Merge Flow");
        assert_eq!(topic.blurb, "How stages merge back to the base branch.");
        assert_eq!(topic.line_count, 5);
    }

    #[test]
    fn test_scan_topics_skips_missing_category_dir() {
        let temp = TempDir::new().unwrap();
        let topics = scan_topics(temp.path()).unwrap();
        assert!(topics.is_empty());
    }

    #[test]
    fn test_generate_index_lists_tier1_and_topics_with_marker() {
        let temp = TempDir::new().unwrap();
        let project_root = temp.path();
        let knowledge = KnowledgeDir::new(project_root);
        knowledge.initialize().unwrap();

        let arch_dir = knowledge.root().join("architecture");
        fs::create_dir_all(&arch_dir).unwrap();
        fs::write(
            arch_dir.join("merge-flow.md"),
            "# Merge Flow\n\n> Merge details.\n",
        )
        .unwrap();

        let content = generate_index(knowledge.root()).unwrap();
        assert!(content.starts_with(GENERATED_MARKER));
        assert!(content.contains("architecture.md"));
        assert!(content.contains("architecture/merge-flow.md"));
        assert!(content.contains("Merge Flow"));
    }

    #[test]
    fn test_generate_index_separates_category_sections_with_blank_lines() {
        let temp = TempDir::new().unwrap();
        let knowledge = KnowledgeDir::new(temp.path());
        knowledge.initialize().unwrap();

        for (category, slug) in [("architecture", "merge-flow"), ("mistakes", "phantom")] {
            let dir = knowledge.root().join(category);
            fs::create_dir_all(&dir).unwrap();
            fs::write(dir.join(format!("{slug}.md")), "# Title\n\n> Blurb.\n").unwrap();
        }

        let content = generate_index(knowledge.root()).unwrap();
        // markdownlint MD022/MD058: a heading that follows a table row directly
        // fails the pre-push markdown lint.
        let lines: Vec<&str> = content.lines().collect();
        for (index, line) in lines.iter().enumerate() {
            if line.starts_with("###") {
                assert_eq!(
                    lines[index - 1],
                    "",
                    "heading {line} must be preceded by a blank line"
                );
            }
        }
    }

    #[test]
    fn test_generate_index_omits_topics_section_when_empty() {
        let temp = TempDir::new().unwrap();
        let knowledge = KnowledgeDir::new(temp.path());
        knowledge.initialize().unwrap();

        let content = generate_index(knowledge.root()).unwrap();
        assert!(!content.contains("Tier 2"));
    }
}
