//! Cross-surface consistency tests for the shared agent-doctrine blocks.
//!
//! Two doctrines are duplicated across surfaces that are owned by DIFFERENT
//! stages and written in DIFFERENT languages, so no single stage can keep them
//! in step and no compiler or linter relates them:
//!
//! * BLOCK-A, the no-verify rule, appears in the signal prefixes generated by
//!   `cache.rs`, in `CLAUDE.md.template` (Rule 5 and worker preambles), and in
//!   the stderr guidance of `hooks/subagent-verify-guard.sh`.
//! * BLOCK-B, the model playbook, appears in `CLAUDE.md.template` (Rule 7) and
//!   in `skills/loom-plan-writer/SKILL.md`.
//!
//! An agent meets these words at the signal, in CLAUDE.md, and at the tool
//! boundary. If the copies drift, one surface silently teaches a rule the
//! others contradict - and a subagent obeying the wrong copy is blocked by the
//! hook with no allowed alternative. These tests pin the copies together.
//!
//! The static surfaces are embedded with `include_str!`, so renaming or moving
//! one of them is a COMPILE error rather than a silently-skipped test.

// BLOCK-A's ABSENCE from the knowledge and knowledge-distill prefixes is
// already pinned by cache.rs's own unit tests; this file covers only the
// cross-surface agreement no single module can check.
use super::super::cache::{generate_integration_verify_stable_prefix, generate_stable_prefix};
use crate::fs::permissions::constants::HOOK_SUBAGENT_VERIFY_GUARD;

const CLAUDE_MD_TEMPLATE: &str = include_str!("../../../../CLAUDE.md.template");
const PLAN_WRITER_SKILL: &str = include_str!("../../../../skills/loom-plan-writer/SKILL.md");
const AGENT_SOFTWARE_ENGINEER: &str = include_str!("../../../../agents/loom-software-engineer.md");
const AGENT_SENIOR_SOFTWARE_ENGINEER: &str =
    include_str!("../../../../agents/loom-senior-software-engineer.md");
const AGENT_CODE_REVIEWER: &str = include_str!("../../../../agents/loom-code-reviewer.md");
const AGENT_ADVISOR: &str = include_str!("../../../../agents/loom-advisor.md");

/// BLOCK-A - the no-verify rule, verbatim. Every surface must carry this text
/// byte for byte; `hooks/subagent-verify-guard.sh` prefixes it with a hook-only
/// "BLOCKED" framing line, which is deliberately not part of the block.
const BLOCK_A: &str = "VERIFICATION IS THE MAIN AGENT'S JOB - NOT YOURS:
- Do NOT verify your work. No full build, no full test suite, no linter, no
  formatter, no type-checker, and never a repeated or looping check.
- AT MOST ONE narrowly-scoped check over the files YOU wrote (e.g.
  `cargo test <your_module>::`), run ONCE. Skip it if you are unsure.
- Report instead: files changed, assumptions made, anything unresolved.
  The MAIN AGENT compiles, tests, lints, and fixes.";

/// BLOCK-B - the model playbook, verbatim.
const BLOCK_B: &str = "1. ORCHESTRATION IS ALWAYS OPUS. Every stage's main agent is opus. The
   orchestrator does NOT implement — it decomposes the work, hands each
   subagent full context, then verifies and commits. That is all.
2. IMPLEMENTATION IS ALWAYS DELEGATED, to as FEW subagents as the work
   allows: haiku (rare — trivial mechanical edits), sonnet (the common
   case), opus (genuinely challenging work). Spawn BY AGENT TYPE.
3. DEBUGGING OR REPEATED FAILURE → spawn a `loom-advisor` (fable) subagent:
   narrow scope, full detail supplied by the orchestrator, advice returned.
   Do not let an implementer thrash on the same failure twice.";

/// Phrasing the no-verify rule RETIRED. Acceptance criteria only grep for the
/// wording a doctrine INTRODUCES, so they cannot catch a surface that still
/// carries the instruction it replaced - which is exactly how the enforcement
/// layer once landed while three guidance files still told subagents to run
/// the suite. Grep for what was retired, not only for what was added.
///
/// Each phrase is assembled with `concat!` so this file never contains one as a
/// contiguous literal. The plan's own acceptance criteria grep this very
/// directory for the retired wording and must find nothing; a checker that
/// trips over its own checklist is worse than no checker. Keep them split, and
/// keep the split out of the middle of a word so the phrase stays readable.
const RETIRED_PHRASES: &[&str] = &[
    concat!("verify your ", "subtree"),
    concat!("verifies its ", "subtree"),
    concat!("Test as ", "you go"),
    concat!("Zero IDE ", "diagnostics"),
];

/// Static guidance surfaces pasted into subagent prompts, as (label, text).
fn guidance_surfaces() -> Vec<(&'static str, &'static str)> {
    vec![
        ("CLAUDE.md.template", CLAUDE_MD_TEMPLATE),
        ("skills/loom-plan-writer/SKILL.md", PLAN_WRITER_SKILL),
        ("agents/loom-software-engineer.md", AGENT_SOFTWARE_ENGINEER),
        (
            "agents/loom-senior-software-engineer.md",
            AGENT_SENIOR_SOFTWARE_ENGINEER,
        ),
        ("agents/loom-code-reviewer.md", AGENT_CODE_REVIEWER),
        ("agents/loom-advisor.md", AGENT_ADVISOR),
    ]
}

#[test]
fn block_a_agrees_across_every_surface() {
    let signal_prefix = generate_stable_prefix();
    let iv_prefix = generate_integration_verify_stable_prefix();

    for (label, text) in [
        ("signal stable prefix", signal_prefix.as_str()),
        ("signal integration-verify prefix", iv_prefix.as_str()),
        ("CLAUDE.md.template", CLAUDE_MD_TEMPLATE),
        ("hooks/subagent-verify-guard.sh", HOOK_SUBAGENT_VERIFY_GUARD),
    ] {
        assert!(
            text.contains(BLOCK_A),
            "{label} does not carry BLOCK-A verbatim. The no-verify rule must be \
             byte-identical on every surface an agent reads it from; reword one \
             and you must reword all of them. Expected to find:\n{BLOCK_A}"
        );
    }
}

#[test]
fn block_b_agrees_across_every_surface() {
    for (label, text) in [
        ("CLAUDE.md.template", CLAUDE_MD_TEMPLATE),
        ("skills/loom-plan-writer/SKILL.md", PLAN_WRITER_SKILL),
    ] {
        assert!(
            text.contains(BLOCK_B),
            "{label} does not carry BLOCK-B verbatim. The model playbook must be \
             byte-identical wherever it appears. Expected to find:\n{BLOCK_B}"
        );
    }
}

#[test]
fn no_guidance_surface_still_tells_a_subagent_to_verify() {
    let signal_prefix = generate_stable_prefix();
    let mut surfaces = guidance_surfaces();
    surfaces.push(("signal stable prefix", signal_prefix.as_str()));

    let mut leftovers = Vec::new();
    for (label, text) in surfaces {
        for phrase in RETIRED_PHRASES {
            if text.contains(phrase) {
                leftovers.push(format!("{label} still contains {phrase:?}"));
            }
        }
    }

    assert!(
        leftovers.is_empty(),
        "guidance surfaces still carry phrasing the no-verify rule retired, so a \
         subagent obeying them would be blocked by hooks/subagent-verify-guard.sh \
         with no allowed alternative:\n  {}",
        leftovers.join("\n  ")
    );
}
