//! Cross-surface consistency tests for the shared agent-doctrine blocks.
//!
//! Two doctrines are duplicated across surfaces that are owned by DIFFERENT
//! stages and written in DIFFERENT languages, so no single stage can keep them
//! in step and no compiler or linter relates them:
//!
//! * BLOCK-A, the no-verify rule, appears in the signal prefixes generated by
//!   `cache.rs`, in `CLAUDE.md.template` (Rule 5 and worker preambles), and in
//!   the stderr guidance of `hooks/subagent-verify-guard.sh`.
//! * BLOCK-B, the model playbook, appears in `CLAUDE.md.template` (Rule 7) and
//!   in `skills/loom-plan-writer/SKILL.md`.
//!
//! A third, BLOCK-C (subagent-waiting), is pinned the same way in the sibling
//! `tests_doctrine_waiting.rs`, split out to keep both files under budget. The
//! tests that pin the emitted STABLE PREFIX / SIGNAL text (rather than the
//! static guidance surfaces BLOCK-A/BLOCK-B live on) are split out the same
//! way into `tests_doctrine_prefixes.rs`.
//! An agent meets these words at the signal, in CLAUDE.md, and at the tool
//! boundary. If the copies drift, one surface silently teaches a rule the
//! others contradict - and a subagent obeying the wrong copy is blocked by the
//! hook with no allowed alternative. These tests pin the copies together.
//!
//! The two singular surfaces are embedded with `include_str!`, so renaming or
//! moving either is a COMPILE error rather than a silently-skipped test. The
//! `agents/` roster is scanned instead, because it grows.
//!
//! BLOCK-A's ABSENCE from the knowledge and knowledge-distill prefixes is
//! already pinned by `cache.rs`'s own unit tests; this file covers only the
//! cross-surface agreement no single module can check.

use std::fs;
use std::path::{Path, PathBuf};

use super::super::cache::{generate_integration_verify_stable_prefix, generate_stable_prefix};
use crate::fs::permissions::constants::HOOK_SUBAGENT_VERIFY_GUARD;

const CLAUDE_MD_TEMPLATE: &str = include_str!("../../../../CLAUDE.md.template");
const PLAN_WRITER_SKILL: &str = include_str!("../../../../skills/loom-plan-writer/SKILL.md");

/// Repo root, resolved from the crate directory at compile time.
fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("loom/ always has a parent - the repo root")
        .to_path_buf()
}

/// Every `agents/*.md` file, read at run time.
///
/// Deliberately a DIRECTORY SCAN rather than a hand-written `include_str!` list:
/// the agent roster grows (this plan alone added `loom-advisor.md`), and a list
/// maintained by hand would quietly stop covering the newest file - which is
/// exactly the surface most likely to be written from a stale template.
fn agent_definitions() -> Vec<(String, String)> {
    let dir = repo_root().join("agents");
    let mut found: Vec<(String, String)> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
        .map(|entry| entry.expect("readable dir entry").path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "md"))
        .map(|path| {
            let text = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
            (
                format!("agents/{}", path.file_name().unwrap().to_string_lossy()),
                text,
            )
        })
        .collect();
    found.sort();

    assert!(
        !found.is_empty(),
        "no agent definitions found in {} - a directory scan that silently \
         matches nothing is a test that silently checks nothing",
        dir.display()
    );
    found
}

/// BLOCK-A - the no-verify rule, verbatim. Every surface must carry this text
/// byte for byte; `hooks/subagent-verify-guard.sh` prefixes it with a hook-only
/// "BLOCKED" framing line, which is deliberately not part of the block.
const BLOCK_A: &str = "VERIFICATION IS THE MAIN AGENT'S JOB - NOT YOURS:
- Do NOT verify your work. No full build, no full test suite, no linter, no
  formatter, no type-checker, and never a repeated or looping check.
- AT MOST ONE narrowly-scoped check over the files YOU wrote (e.g.
  `cargo test <your_module>::`), run ONCE. Skip it if you are unsure.
- Report instead: files changed, assumptions made, anything unresolved.
  The MAIN AGENT compiles, tests, lints, and fixes.";

/// BLOCK-B - the model playbook, verbatim.
///
/// A raw literal: the block quotes the phrases an orchestrator uses to talk
/// itself into implementing ("I have diagnosed it"), so it carries `"` inside.
const BLOCK_B: &str = r#"1. THE MAIN AGENT NEVER IMPLEMENTS — WHATEVER MODEL IT RUNS (hard stop 6).
   Every stage's main agent is an orchestrator: it decomposes the work, hands
   each subagent full context, then verifies and commits. That is all. This
   holds identically for an opus session and a fable session; a session running
   an expensive model is MORE obliged to delegate, not less.
2. INVESTIGATION ENDS IN A BRIEF, NOT IN AN EDIT. The moment you finish reading
   the code and know what the fix is, you are at the delegation boundary — that
   understanding is exactly what makes a cheap subagent effective. Write it down
   (file:line, root cause, the change to make, signatures, patterns to match,
   acceptance) and spawn. Do not slide from "I have diagnosed it" into "I will
   just type it"; the diagnosis being yours does not make the typing yours.
3. IMPLEMENTATION IS ALWAYS DELEGATED, to as FEW subagents as the work allows, at
   the CHEAPEST tier that can do the piece. Pick PER SUBAGENT by what that piece
   needs, never once for the whole stage, and default downward: codex
   gpt-5.6-luna for boilerplate, scaffolding, and simple unit tests; SONNET
   (loom-software-engineer) or codex gpt-5.6-terra for common implementation and
   integration tests — this is the default lane and most work belongs here; OPUS
   (loom-senior-software-engineer) for mainstream architecture and algorithm
   implementation; FABLE only for visual/UI design, a bug that survived a
   delegated fix attempt, or extremely challenging algorithmic design. Codex
   tiers (effort xhigh, via loom-codex-forwarder) exist only on stages listing
   codex in implementers AND when the codex CLI + plugin are installed;
   otherwise that work goes to sonnet (loom warns at startup when a stage lists
   codex it cannot use). Verification NEVER delegates - the orchestrator
   verifies and commits. Spawn BY AGENT TYPE.
4. ESCALATE ON EVIDENCE, NOT ON HUNCH. Start at the cheapest plausible tier. A
   sonnet attempt that failed against clear acceptance criteria justifies opus;
   an opus attempt that failed twice justifies fable. "This feels subtle" does
   not. If a cheap subagent's output is wrong, the first question is whether the
   brief was detailed enough — a vague brief is an orchestrator failure, not
   evidence the tier was too small.
5. DEBUGGING OR REPEATED FAILURE → spawn a `loom-advisor` (fable) subagent:
   narrow scope, full detail supplied by the orchestrator, advice returned, no
   writes. Its diagnosis then feeds a sonnet or opus implementer per point 2.
   Do not let an implementer thrash on the same failure twice."#;

/// Phrasing RETIRED doctrines used, across the no-verify rule (BLOCK-A) and the
/// subagent-waiting rule (BLOCK-C). Acceptance criteria only grep for the
/// wording a doctrine INTRODUCES, so they cannot catch a surface that still
/// carries the instruction it replaced - which is exactly how the enforcement
/// layer once landed while three guidance files still told subagents to run
/// the suite. Grep for what was retired, not only for what was added.
///
/// Each phrase is assembled with `concat!` so this file never contains one as a
/// contiguous literal. The plan's own acceptance criteria grep this very
/// directory for the retired wording and must find nothing; a checker that
/// trips over its own checklist is worse than no checker. Keep them split, and
/// keep the split out of the middle of a word so the phrase stays readable.
const RETIRED_PHRASES: &[&str] = &[
    concat!("verify your ", "subtree"),
    concat!("verifies its ", "subtree"),
    concat!("Test as ", "you go"),
    concat!("Zero IDE ", "diagnostics"),
    concat!("haiku stays rare", " and trivial"),
    concat!("haiku (rare, trivial ", "mechanical edits)"),
    concat!("take the work ", "over"),
    concat!("report back ", "within"),
    concat!("hard ceiling on any", " single check"),
    // BLOCK-C: superseded by `loom subagents watch`'s own deadline/state.
    concat!("a check firing is NOT", " a deadline"),
    concat!("MUST carry a liveness", " signal"),
];

/// Every static guidance surface pasted into a subagent prompt, as (label, text).
fn guidance_surfaces() -> Vec<(String, String)> {
    let mut surfaces = vec![
        (
            "CLAUDE.md.template".to_string(),
            CLAUDE_MD_TEMPLATE.to_string(),
        ),
        (
            "skills/loom-plan-writer/SKILL.md".to_string(),
            PLAN_WRITER_SKILL.to_string(),
        ),
    ];
    surfaces.extend(agent_definitions());
    surfaces
}

#[test]
fn block_a_agrees_across_every_surface() {
    let signal_prefix = generate_stable_prefix();
    let iv_prefix = generate_integration_verify_stable_prefix();

    for (label, text) in [
        ("signal stable prefix", signal_prefix.as_str()),
        ("signal integration-verify prefix", iv_prefix.as_str()),
        ("CLAUDE.md.template", CLAUDE_MD_TEMPLATE),
        ("hooks/subagent-verify-guard.sh", HOOK_SUBAGENT_VERIFY_GUARD),
    ] {
        assert!(
            text.contains(BLOCK_A),
            "{label} does not carry BLOCK-A verbatim. The no-verify rule must be \
             byte-identical on every surface an agent reads it from; reword one \
             and you must reword all of them. Expected to find:\n{BLOCK_A}"
        );
    }
}

#[test]
fn block_b_agrees_across_every_surface() {
    for (label, text) in [
        ("CLAUDE.md.template", CLAUDE_MD_TEMPLATE),
        ("skills/loom-plan-writer/SKILL.md", PLAN_WRITER_SKILL),
    ] {
        assert!(
            text.contains(BLOCK_B),
            "{label} does not carry BLOCK-B verbatim. The model playbook must be \
             byte-identical wherever it appears. Expected to find:\n{BLOCK_B}"
        );
    }

    // BLOCK-B names the codex lane's model and effort as prose literals, so
    // equality with the surfaces above is not enough: editing the constants in
    // codex.rs would leave every surface agreeing on a RETIRED model and this
    // test still green. Pin the prose to the constants the signal interpolates.
    assert!(
        BLOCK_B.contains(crate::codex::CODEX_IMPLEMENTER_MODEL_TERRA),
        "BLOCK-B must name CODEX_IMPLEMENTER_MODEL_TERRA ({}); update every surface \
         when the constant changes",
        crate::codex::CODEX_IMPLEMENTER_MODEL_TERRA
    );
    assert!(
        BLOCK_B.contains(crate::codex::CODEX_IMPLEMENTER_MODEL_LUNA),
        "BLOCK-B must name CODEX_IMPLEMENTER_MODEL_LUNA ({}); update every surface \
         when the constant changes",
        crate::codex::CODEX_IMPLEMENTER_MODEL_LUNA
    );
    assert!(
        BLOCK_B.contains(crate::codex::CODEX_IMPLEMENTER_EFFORT),
        "BLOCK-B must name CODEX_IMPLEMENTER_EFFORT ({}); update every surface \
         when the constant changes",
        crate::codex::CODEX_IMPLEMENTER_EFFORT
    );
}

#[test]
fn codex_forward_sentinel_agrees_across_surfaces() {
    use crate::codex::CODEX_FORWARD_SENTINEL;
    use crate::fs::permissions::constants::HOOK_CODEX_FORWARD_GUARD;

    // The hook enforces exactly the token the signal doctrine mandates. The
    // signal side is pinned in tests_cache.rs (the generated section contains
    // the constant); this side pins the shell literal to the same constant.
    assert!(
        HOOK_CODEX_FORWARD_GUARD.contains(CODEX_FORWARD_SENTINEL),
        "hooks/codex-forward-guard.sh must grep for CODEX_FORWARD_SENTINEL \
         ({CODEX_FORWARD_SENTINEL}); a hook keyed on a drifted token enforces \
         nothing"
    );

    let (_, forwarder) = agent_definitions()
        .into_iter()
        .find(|(label, _)| label == "agents/loom-codex-forwarder.md")
        .expect(
            "agents/loom-codex-forwarder.md must exist - the signal doctrine \
             spawns codex work by that agent type",
        );
    for needle in [CODEX_FORWARD_SENTINEL, "codex-forward.sh"] {
        assert!(
            forwarder.contains(needle),
            "agents/loom-codex-forwarder.md must mention {needle:?} - the \
             forwarder contract, the hook, and the signal doctrine describe \
             one protocol"
        );
    }

    // The playbook surfaces route codex work through the forwarder, never a
    // direct spawn of the plugin wrapper (whose tools restriction is not
    // enforced on this spawn path - observed implementing instead of
    // forwarding, 2026-08-07).
    for (label, text) in [
        ("CLAUDE.md.template", CLAUDE_MD_TEMPLATE),
        ("skills/loom-plan-writer/SKILL.md", PLAN_WRITER_SKILL),
    ] {
        assert!(
            text.contains("loom-codex-forwarder"),
            "{label} must route codex work through loom-codex-forwarder"
        );
    }
}

#[test]
fn no_guidance_surface_still_tells_a_subagent_to_verify() {
    let mut surfaces = guidance_surfaces();
    surfaces.push(("signal stable prefix".to_string(), generate_stable_prefix()));

    let mut leftovers = Vec::new();
    for (label, text) in surfaces {
        for phrase in RETIRED_PHRASES {
            if text.contains(phrase) {
                leftovers.push(format!("{label} still contains {phrase:?}"));
            }
        }
    }

    assert!(
        leftovers.is_empty(),
        "guidance surfaces still carry phrasing the no-verify rule retired, so a \
         subagent obeying them would be blocked by hooks/subagent-verify-guard.sh \
         with no allowed alternative:\n  {}",
        leftovers.join("\n  ")
    );
}

// The tests pinning the STABLE PREFIX / emitted-signal text - the settled-
// completion doctrine, the subagent-budget cadence framing, and the
// KNOWLEDGE_CONSUMPTION_CONTRACT byte-equality check - live in the sibling
// `tests_doctrine_prefixes.rs`, split out to keep this file under budget.
//
// The "both renderers emit the brief" tests live in tests_brief.rs, beside
// `sample_context_pack` - this file already sits near its own line budget and
// those tests are about the brief pipeline, not cross-surface doctrine.
