pub const BASH_COMPLETION: &str = r##"#!/usr/bin/env bash
# loom shell completions for bash
# Generated by: loom completions bash
# Re-generate with: loom completions bash > ~/.local/share/bash-completion/completions/loom
#   or: eval "$(loom completions bash)"

_loom() {
    local cur prev
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    local IFS=$'\n'
    local completions
    completions=$(loom complete bash "$PWD" "${COMP_LINE}" "$cur" "$prev" 2>/dev/null)

    if [[ -n "$completions" ]]; then
        COMPREPLY=()
        while IFS= read -r line; do
            COMPREPLY+=("$line")
        done <<< "$completions"
    fi
}

complete -o default -o bashdefault -F _loom loom
"##;
