pub const ZSH_COMPLETION: &str = r##"#compdef loom
# loom shell completions for zsh
# Generated by: loom completions zsh
# Install: loom completions zsh > "${fpath[1]}/_loom"
#   or: eval "$(loom completions zsh)"

_loom() {
    local -a completions
    local cur prev

    # Handle edge case: CURRENT=1 means completing the command itself
    if (( CURRENT > 1 )); then
        cur="${words[CURRENT]}"
    else
        cur=""
    fi
    if (( CURRENT > 2 )); then
        prev="${words[CURRENT-1]}"
    else
        prev=""
    fi

    completions=(${(f)"$(loom complete zsh "$PWD" "${words[*]}" "$cur" "$prev" 2>/dev/null)"})

    if (( ${#completions} > 0 )); then
        compadd -U -- "${completions[@]}"
    fi
}

_loom "$@"
"##;
